baseURL = "/"
languageCode = "en-us"
title = "Caddie  Service"
themesDir = "themes"
theme = "hugo-hero-theme"

[params]
  google_analytics_id=""

  [params.homepage_meta_tags]
    meta_description = "We’re a design-driven development agency led by a team of world-class developers, designers and consultants."
    meta_og_title = "Caddie Service Development Agency"
    meta_og_type = "website"
    meta_og_url = "https://caddie-service.github.io"
    meta_og_image = "https://caddie-service.github.io/images/caddieservice-logo.png"
    meta_og_description = "We’re a design-driven development agency led by a team of world-class developers, designers and consultants."
    
    meta_twitter_card = "summary"
    meta_twitter_site = "@caddieservice"
    meta_twitter_creator = "@caddieservice"

[[menu.main]]
    name = "Work"
    url = "/work/"
    weight = 1

[[menu.main]]
    name = "Services"
    url = "/services/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"