baseURL = "/"
languageCode = "en-us"
title = "Caddie  Service"
themesDir = "themes"
theme = "hugo-hero-theme"

[params]
  google_analytics_id=""

  [params.homepage_meta_tags]
    meta_description = "Caddie"
    meta_og_title = "Caddie"
    meta_og_type = "website"
    meta_og_url = "https://example.com.com"
    meta_og_image = ""
    meta_og_description = ""
    meta_twitter_card = "summary"
    meta_twitter_site = ""
    meta_twitter_creator = ""

[[menu.main]]
    name = "Work"
    url = "/work/"
    weight = 1

[[menu.main]]
    name = "Services"
    url = "/services/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"